name: Test code on Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - uses: actions/checkout@v2

      - name: Cache go modules
        uses: actions/cache@v2
        with:
          path: $GOPATH/pkg/mod
          key: ${{ runner.os }}-go-modules-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-modules-${{ hashFiles('go.sum') }}
            ${{ runner.os }}-go-modules-

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./...
